### PR TITLE
add wsgi file extension support

### PR DESCRIPTION
**Pull request by luca76**
add python wsgi file extension support (apache2 mod_wsgi)

### CODE REVIEW

**Comment by ambv** [comment]
You need to also edit grammars/src/MagicPython.syntax.yaml.

**Comment by 1st1** [comment]
> You need to also edit grammars/src/MagicPython.syntax.yaml.

True. Ideally, only `syntax.yaml` needs to be amended; then run `make test` and then commit everything.

**Comment by 1st1** [comment]
Closing this one (in favour of https://github.com/MagicStack/MagicPython/pull/67)

**Comment by 1st1** [comment]
> Closing this one (in favour of #67)

Turns out `.wsgi` still needs to be added.

**Pull request closed without merging**
