### PR TITLE
Add ``match`` and ``case`` syntax Python 3.10

### PR DESCRIPTION
**Pull request by cdce8p**
Python 3.10 will add pattern matching with the `match` and `case` keywords.
This PR adds a regular expression to recognize them as `keyword.control.flow.python` if present in a `match` statement. Since they are only `soft` keywords and still allowed as normal variable names, it's not possible to simply add them to the list of the other keywords.

Closes: #235

**Example**
```py
def http_error(status: int):
    match status:
        case 400:
            return "Bad request"
        case 404:
            return "Not found"
        case 418:
            return "I'm a teapot"
        case _:
            return "Default case, unreachable"
```

Screen Shot 2021-05-01 at 15 21 44

### CODE REVIEW

**Comment by norabelrose** [comment]
It's no super clear to me why this PR is "failing" the CI tests. When I look at the logs it looks like none of the actual MagicPython tests fail, but later some bizarre error is thrown from inside Atom. When I clone this branch and run the tests myself, they all pass.

Can we try to get this merged soon? Does something need to be fixed with the CI?

**Comment by ConstantinGahr** [comment]
Hi, whats the current status of this pull request? I'd love to have `match case` statements.

**Comment by tiararosebiezetta** [comment]
I am waiting for this pull request too.

**Comment by ruthus18** [comment]
Any updates?

**Comment by spagh-eddie** [comment]
I too would like this

**Comment by wszqkzqk** [comment]
Nice feature!

**Comment by neumond** [comment]
This isn't true that built-in python highlighter of VS Code supports match/case.
I've built this pull request and it works for me. Haven't tested it thoroughly though.

For Ubuntu 22.04 and snap distribution of Codium:

```sh
sudo apt install nodejs npm
git clone 'https://github.com/MagicStack/MagicPython'
cd MagicPython/
git fetch origin pull/237/head
git checkout FETCH_HEAD
make
make release
npm install --dev cson
./node_modules/.bin/cson2json grammars/MagicPython.cson > grammars/MagicPython.tmLanguage.json
sudo mount --bind grammars/MagicPython.tmLanguage.json /snap/codium/current/usr/share/codium/resources/app/extensions/python/syntaxes/MagicPython.tmLanguage.json
```

This isn't permanent fix, it requires mounting patched json after each reboot. Json itself could be made more compact, as the one shipped with codium.

**Pull request closed without merging**
