### PR TITLE
Tokenize `@` and `.` in decorators

### LINKED ISSUE #105: Scope `@` in decorators as punctuation
Can `@` have its own scope? It would be handy as `punctuation.definition.decorator`, similarly to `$` scoped as `punctuation.definition.variable` in php for example.

### PR DESCRIPTION
**Pull request by chbk**
Fixes #105 

`@` in decorators is now `source.python` > `meta.function.decorator.python` > `entity.name.function.decorator.python` > `punctuation.definition.decorator.python`

`.` in decorators is now `source.python` > `meta.function.decorator.python` > `entity.name.function.decorator.python` > `punctuation.separator.period.python`

### CODE REVIEW

**Comment by chbk** [comment]
The CI build fails on master too. Doesn't seem related to this PR.

**Comment by chbk** [comment]
I have the same build failure on master :thinking:

**Comment by chbk** [comment]
@1st1 Should I submit a PR to fix the CI build? `git checkout master && make test` gives me the same errors

**Comment by chbk** [comment]
@vpetrovykh @1st1 @elprans Could one of you review this?

**Comment by 1st1** [comment]
Thank you!

**Pull request merged**
